### PR TITLE
Unit tests pandas fixes

### PR DESCRIPTION
**Pull request by FineArtMaths**
To test, first run pip3 install pandas --upgrade.

### CODE REVIEW

**Review by hartj2 — CHANGES_REQUESTED** [review]
Hey :) all looks good, except the Coalesced test is failing due to the attached error. Could you please take a look at this before I merge this branch? thank you loads! @FineArtMaths 
image

**Comment by FineArtMaths** [comment]
Good catch -- that was failing under the old Pandas but not the new one, so I only saw the problem when I downgraded again. I'll add an explicit ordering to the columns of test_df for that one since coalesce() depends on that.

**Comment by FineArtMaths** [comment]
Tests should be passing with both versions of pandas now!

**Review by hartj2 — APPROVED** [review]
Thanks so much, all is passing now :) happy for you to merge when ready! @FineArtMaths

**Pull request merged**
